# Generated by Django 6.0.7 on 2026-07-14 01:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('level_in_backroom', models.IntegerField(default=0)),
                ('min_level', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADD', 'Stock Added'), ('REMOVE', 'Stock Removed'), ('SALE', 'Vending Sale'), ('ADJUST', 'Manual Adjustment')], max_length=10)),
                ('source', models.CharField(choices=[('USER', 'User/Manual'), ('TASK', 'Background Task')], default='USER', max_length=10)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='items.item')),
            ],
        ),
    ]
