# Generated by Django 6.0.7 on 2026-07-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_order', models.DecimalField(decimal_places=2, help_text='Cost to buy one unit/case', max_digits=10)),
                ('amount_received_per_order', models.IntegerField(help_text='e.g., 24 (if you buy 1 case and get 24 cans)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Calculated price per individual item', max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_connections', to='items.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='vendors.vendor')),
            ],
        ),
    ]
